version: '3'

networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  todo-app:
    build:
      context: .  # Ensure this path is correct
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    depends_on:
      - todo-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config for reverse proxy
      - ./certs:/etc/nginx/certs            # SSL certificates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

volumes:
  postgres_data:
